relativeURLs = true
languageCode = 'en-us'
title = 'Giulia Valenti'
sectionPagesMenu = "main"
theme = 'academimal'
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD Candidate, Ca'Foscari University"
    logo = "ap_headshot_1.jpg" 

    
