relativeURLs = true
title = "Giulia Valenti"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "Postdoctoral Researcher, Fondazione Eni Enrico Mattei (FEEM)"
    logo = "profile.png" 
    
