relativeURLs = true
title = "Giulia Valenti"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"
ignorefiles = [ "hugo_travis_ci", ".travis.yml" ]

[params]
    shortbio = "PhD candidate at Ca' Foscari University, Venice"
    logo = "Rao_headshot_berkeley.jpg" 
    
